package com.nordnet.zabuza.ws.entities.constants;

/**
 * Level.
 *
 * this enum is auto generated by the com.nordnet.common project : entities-maven-plugin,
 * do not edit this class directly, all change will be lost on next build ...
 *
 * @author MMORTIER, JLDANSOU
 *
 */
public enum Level {

	/** {@link Level} OK. */
	OK,
	/** {@link Level} WARNING. */
	WARNING,
	/** {@link Level} CRITICAL. */
	CRITICAL,
	/** {@link Level} UNKNOWN. */
	UNKNOWN;

}
