package com.nordnet.zabuza.ws.entities.test;

import static com.nordnet.common.valueObject.utils.JSon.canBeJSonSerialized;
import static com.nordnet.common.valueObject.utils.Utils.hasProtectedEmptyConstructorEqualsAndHashCodeAndCompareTo;
import static org.junit.Assert.assertTrue;

import org.junit.Test;

import com.nordnet.common.valueObject.identifier.Identifier;
import com.nordnet.zabuza.ws.entities.ConnectionDataBase;

/**
 * generic test for {@link ConnectionDataBase} entity.
 *
 * this class is auto generated by the com.nordnet.common project : entities-maven-plugin,
 * do not edit this class directly, all change will be lost on next build ...
 */
@SuppressWarnings("unused")
public class ConnectionDataBaseTest extends GlobalTestCase {

	/**
	 * test  for ConnectionDataBase  methods.
	 * <li> constructors,
	 * <li> {@link ConnectionDataBase#equals(Object)},
	 * <li> {@link ConnectionDataBase#hashCode()},
	 * <li> {@link ConnectionDataBase#toString()}
	 * <li> {@link ConnectionDataBase#compareTo(ConnectionDataBase)}
	 */
	@Test
	public void successTest() {
		ConnectionDataBase tmp = ConnectionDataBase.builder()
			.identifier(Identifier.build("identifier"))
			.host("String")
			.schema("String")
			.user("String")
			.userPassword("String").build();
		assertTrue(hasProtectedEmptyConstructorEqualsAndHashCodeAndCompareTo(ConnectionDataBase.class, tmp));
		assertTrue(canBeJSonSerialized(tmp));
	}
}
