package com.nordnet.zabuza.ws.entities.test;

import static com.nordnet.common.valueObject.utils.JSon.canBeJSonSerialized;
import static com.nordnet.common.valueObject.utils.Utils.hasProtectedEmptyConstructorEqualsAndHashCodeAndCompareTo;
import static org.junit.Assert.assertTrue;

import org.junit.Test;

import com.nordnet.common.valueObject.identifier.Identifier;
import static com.nordnet.zabuza.ws.entities.constants.Level.OK;
import com.nordnet.zabuza.ws.entities.Rule;

/**
 * generic test for {@link Rule} entity.
 *
 * this class is auto generated by the com.nordnet.common project : entities-maven-plugin,
 * do not edit this class directly, all change will be lost on next build ...
 */
@SuppressWarnings("unused")
public class RuleTest extends GlobalTestCase {

	/**
	 * test  for Rule  methods.
	 * <li> constructors,
	 * <li> {@link Rule#equals(Object)},
	 * <li> {@link Rule#hashCode()},
	 * <li> {@link Rule#toString()}
	 * <li> {@link Rule#compareTo(Rule)}
	 */
	@Test
	public void successTest() {
		Rule tmp = Rule.builder()
			.connectionDataBase(Identifier.build("identifier"))
			.descriptif("String")
			.identifier(Identifier.build("identifier"))
			.level(OK)
			.parent(Identifier.build("identifier"))
			.query(Identifier.build("identifier")).build();
		assertTrue(hasProtectedEmptyConstructorEqualsAndHashCodeAndCompareTo(Rule.class, tmp));
		assertTrue(canBeJSonSerialized(tmp));
	}
}
